#!/bin/sh

#
#Ez a script az aktualis konyvtarban levo osszes fajlt ISO-8859-1 
#kodolasunak tekinti es atkodolja UTF-8 ba
#es a fajlokat valtoztlan nevvel egy KOD nevu alkonyvtarba helyezi
#

mkdir KOD;

#sikerult letrehozni a konyvtarat
if [ $? -eq 0 ] ; then
    for file in `ls`; do
    
	#csak ha fajl-rol van szo
	if [ -f $file ] ; then
	
    	    iconv --from-code=iso-8859-1 --to-code=utf8 ./$file > ./KOD/$file	

	fi

	
    done
fi