#!/bin/bash

#
#A parameterkent megadott szot keresi az aktualis konyvtar fajljaiban
#
#su root -c "

#tobb parameter is lehet, de legalabb egy
if [ $# -gt 0 ] ; then

    param=""
    eloszor=0
    
    until [ $# -eq 0 ] ; do

	if [ $eloszor != 0 ] ; then	
	    param=$param" "		    
        fi
	eloszor=1
	param=$param$1
	shift
    done

    #param=$param"\""
    
    for file in `ls -a`; do
        sor=`cat $file 2>/dev/null | grep -n "$param"`
        if [ -n "$sor" ]; then
        	echo "$file":  $sor
        fi     
    done #"
else
    echo Usage $0 " <keresett kifejezes>"
fi
