#!/bin/sh
 
#
#Ez a script a parameterkent megadott flv tipusu fajlt alakitja at avi fajl-la
#

vissza=1
output=""
lehetsegeskiter=flv:wmv:mov:avi
csere="avi"

#ha van parameter, akkor tovabb mehetek
if [ $# -eq 1 ] ;then

    #ha az aktualis fajl letezik es olvashato, akkor tovabb mehetek
    if [ -r $1 ] ;then    
	
	#vegig megyek a lehetseges kiterjeszteseken
	for kit in `echo $lehetsegeskiter|tr ":" " "` ; do
	
	    #ha az aktualis fajlnak ertelmes kiterjesztese van, akkor mehet tovabb
	    if [ `echo $1 | grep -c '\.'$kit'$'` -ne 0 ] ; then
		#echo ertelmes kiterjesztes
		vissza=0;
		break;		
	    fi
	
	done

	#ha ertelmes kiterjesztese volt a fajlnak, akkor tovabb mehetek		
	if [ $vissza -eq 0 ] ; then
	
	    telhos=`echo $1 |wc -c`
	    kithos=`echo $kit | wc -c`
	    bashos=`expr $telhos - $kithos`
	    
	    ujfajl=`echo $1 | cut -c0-$bashos -`$csere

	    #ha az uj fajl megegyezik az eredetivel vagyis pld avi kiterjesztesu fajlt 
	    #akarunk avi kiterjesztesuve alakitani, akkor az uj fajl neve a regi fajl
	    #plusz az uj kiterjesztes lesz (nem csereli le a kiterjesztest)
	    if [ $1 = $ujfajl ] ; then
	    
		ujfajl=$ujfajl.$csere
	    fi
	    
	    #ha letezik az uj fajl, akkor hibajelzes utan kilep, nem kodol
	    if [ -f $ujfajl ] ; then
	    
		echo $1 " fájl kódolása nem történt meg mert a " $ujfajl " fájl már létezik"
	    
	    #mehet a kodolas
	    else

#		mencoder $1 -o $ujfajl -ovc lavc -oac mp3lame 

mencoder $1 -o $ujfajl -ovc xvid -oac mp3lame -xvidencopts bitrate=700	    	    
	    fi
	
	fi	
	
	vissza=0
    else
	echo \"$1\" file name is bad
    fi
else
    echo Usage: $0 file_name
fi


